//! Temporary, pinned shipped metadata for the pre-registry firehose checkout.
//! Staging/builtins.json may replace this table with exact release signatures.
use super::convert::Signatures;
use anyhow::Result;
pub fn signatures() -> Result<Signatures> {
    let mut signatures = Signatures::default();
    signatures.add(serde_json::from_str(include_str!(
        "../../../../packs/agents/agent.claude/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../packs/agents/agent.codex/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../packs/agents/agent.devin/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../packs/agents/agent.review/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../packs/agents/agent.run/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../packs/agents/decide.llm/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../packs/git/gh.pr/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../packs/git/gh.pr_wait/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../packs/git/gh.run_cancel/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../packs/git/gh.run_latest/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../packs/git/git.head/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../packs/git/git.merge/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../packs/git/git.push/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../packs/git/git.rebase/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../packs/git/git.worktree/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../packs/git/git.worktree_rm/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../src/sluice/fns/core.collect/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../src/sluice/fns/core.echo/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../src/sluice/fns/core.external/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../src/sluice/fns/core.format/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../src/sluice/fns/inbox.ask/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../src/sluice/fns/inline.bash/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../src/sluice/fns/inline.python/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../src/sluice/fns/thread.post/fn.json"
    ))?)?;
    signatures.add(serde_json::from_str(include_str!(
        "../../../../src/sluice/fns/thread.wait/fn.json"
    ))?)?;
    Ok(signatures)
}

pub fn shipped() -> std::collections::BTreeMap<String, std::collections::BTreeMap<String, String>> {
    let mut out = std::collections::BTreeMap::new();
    {
        let mut files = std::collections::BTreeMap::new();
        files.insert(
            "fn.json".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/agent.claude/fn.json"
            )),
        );
        files.insert(
            "icon.svg".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/agent.claude/icon.svg"
            )),
        );
        files.insert(
            "main.py".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/agent.claude/main.py"
            )),
        );
        out.insert("agent.claude".into(), files);
    }
    {
        let mut files = std::collections::BTreeMap::new();
        files.insert(
            "fn.json".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/agent.codex/fn.json"
            )),
        );
        files.insert(
            "icon.svg".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/agent.codex/icon.svg"
            )),
        );
        files.insert(
            "main.py".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/agent.codex/main.py"
            )),
        );
        out.insert("agent.codex".into(), files);
    }
    {
        let mut files = std::collections::BTreeMap::new();
        files.insert(
            "fn.json".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/agent.devin/fn.json"
            )),
        );
        files.insert(
            "icon.svg".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/agent.devin/icon.svg"
            )),
        );
        files.insert(
            "main.py".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/agent.devin/main.py"
            )),
        );
        out.insert("agent.devin".into(), files);
    }
    {
        let mut files = std::collections::BTreeMap::new();
        files.insert(
            "fn.json".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/agent.review/fn.json"
            )),
        );
        files.insert(
            "icon.svg".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/agent.review/icon.svg"
            )),
        );
        files.insert(
            "main.py".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/agent.review/main.py"
            )),
        );
        out.insert("agent.review".into(), files);
    }
    {
        let mut files = std::collections::BTreeMap::new();
        files.insert(
            "fn.json".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/agent.run/fn.json"
            )),
        );
        files.insert(
            "icon.svg".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/agent.run/icon.svg"
            )),
        );
        files.insert(
            "main.py".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/agent.run/main.py"
            )),
        );
        out.insert("agent.run".into(), files);
    }
    {
        let mut files = std::collections::BTreeMap::new();
        files.insert(
            "fn.json".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/decide.llm/fn.json"
            )),
        );
        files.insert(
            "icon.svg".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/decide.llm/icon.svg"
            )),
        );
        files.insert(
            "main.py".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/agents/decide.llm/main.py"
            )),
        );
        out.insert("decide.llm".into(), files);
    }
    {
        let mut files = std::collections::BTreeMap::new();
        files.insert(
            "fn.json".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/gh.pr/fn.json"
            )),
        );
        files.insert(
            "icon.svg".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/gh.pr/icon.svg"
            )),
        );
        files.insert(
            "main.py".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/gh.pr/main.py"
            )),
        );
        out.insert("gh.pr".into(), files);
    }
    {
        let mut files = std::collections::BTreeMap::new();
        files.insert(
            "fn.json".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/gh.pr_wait/fn.json"
            )),
        );
        files.insert(
            "icon.svg".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/gh.pr_wait/icon.svg"
            )),
        );
        files.insert(
            "main.py".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/gh.pr_wait/main.py"
            )),
        );
        out.insert("gh.pr_wait".into(), files);
    }
    {
        let mut files = std::collections::BTreeMap::new();
        files.insert(
            "fn.json".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/gh.run_cancel/fn.json"
            )),
        );
        files.insert(
            "icon.svg".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/gh.run_cancel/icon.svg"
            )),
        );
        files.insert(
            "main.py".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/gh.run_cancel/main.py"
            )),
        );
        out.insert("gh.run_cancel".into(), files);
    }
    {
        let mut files = std::collections::BTreeMap::new();
        files.insert(
            "fn.json".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/gh.run_latest/fn.json"
            )),
        );
        files.insert(
            "icon.svg".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/gh.run_latest/icon.svg"
            )),
        );
        files.insert(
            "main.py".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/gh.run_latest/main.py"
            )),
        );
        out.insert("gh.run_latest".into(), files);
    }
    {
        let mut files = std::collections::BTreeMap::new();
        files.insert(
            "fn.json".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.head/fn.json"
            )),
        );
        files.insert(
            "icon.svg".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.head/icon.svg"
            )),
        );
        files.insert(
            "main.py".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.head/main.py"
            )),
        );
        out.insert("git.head".into(), files);
    }
    {
        let mut files = std::collections::BTreeMap::new();
        files.insert(
            "fn.json".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.merge/fn.json"
            )),
        );
        files.insert(
            "icon.svg".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.merge/icon.svg"
            )),
        );
        files.insert(
            "main.py".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.merge/main.py"
            )),
        );
        out.insert("git.merge".into(), files);
    }
    {
        let mut files = std::collections::BTreeMap::new();
        files.insert(
            "fn.json".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.push/fn.json"
            )),
        );
        files.insert(
            "icon.svg".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.push/icon.svg"
            )),
        );
        files.insert(
            "main.py".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.push/main.py"
            )),
        );
        out.insert("git.push".into(), files);
    }
    {
        let mut files = std::collections::BTreeMap::new();
        files.insert(
            "fn.json".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.rebase/fn.json"
            )),
        );
        files.insert(
            "icon.svg".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.rebase/icon.svg"
            )),
        );
        files.insert(
            "main.py".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.rebase/main.py"
            )),
        );
        out.insert("git.rebase".into(), files);
    }
    {
        let mut files = std::collections::BTreeMap::new();
        files.insert(
            "fn.json".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.worktree/fn.json"
            )),
        );
        files.insert(
            "icon.svg".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.worktree/icon.svg"
            )),
        );
        files.insert(
            "main.py".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.worktree/main.py"
            )),
        );
        out.insert("git.worktree".into(), files);
    }
    {
        let mut files = std::collections::BTreeMap::new();
        files.insert(
            "fn.json".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.worktree_rm/fn.json"
            )),
        );
        files.insert(
            "icon.svg".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.worktree_rm/icon.svg"
            )),
        );
        files.insert(
            "main.py".into(),
            sluice_store::artifacts::fingerprint(include_bytes!(
                "../../../../packs/git/git.worktree_rm/main.py"
            )),
        );
        out.insert("git.worktree_rm".into(), files);
    }
    out
}

pub fn shipped_helpers() -> std::collections::BTreeMap<String, String> {
    let mut out = std::collections::BTreeMap::new();
    out.insert(
        "_agents/engines.py".into(),
        sluice_store::artifacts::fingerprint(include_bytes!(
            "../../../../packs/agents/_agents/engines.py"
        )),
    );
    out.insert(
        "_agents/native/__init__.py".into(),
        sluice_store::artifacts::fingerprint(include_bytes!(
            "../../../../packs/agents/_agents/native/__init__.py"
        )),
    );
    out.insert(
        "_agents/native/claude.py".into(),
        sluice_store::artifacts::fingerprint(include_bytes!(
            "../../../../packs/agents/_agents/native/claude.py"
        )),
    );
    out.insert(
        "_agents/native/codex.py".into(),
        sluice_store::artifacts::fingerprint(include_bytes!(
            "../../../../packs/agents/_agents/native/codex.py"
        )),
    );
    out.insert(
        "_agents/native/devin.py".into(),
        sluice_store::artifacts::fingerprint(include_bytes!(
            "../../../../packs/agents/_agents/native/devin.py"
        )),
    );
    out.insert(
        "_agents/native/paste.py".into(),
        sluice_store::artifacts::fingerprint(include_bytes!(
            "../../../../packs/agents/_agents/native/paste.py"
        )),
    );
    out.insert(
        "_agents/native/processes.py".into(),
        sluice_store::artifacts::fingerprint(include_bytes!(
            "../../../../packs/agents/_agents/native/processes.py"
        )),
    );
    out.insert(
        "_agents/native/reprime.py".into(),
        sluice_store::artifacts::fingerprint(include_bytes!(
            "../../../../packs/agents/_agents/native/reprime.py"
        )),
    );
    out.insert(
        "_agents/native/supervisor.py".into(),
        sluice_store::artifacts::fingerprint(include_bytes!(
            "../../../../packs/agents/_agents/native/supervisor.py"
        )),
    );
    out.insert(
        "_agents/native/tmux.py".into(),
        sluice_store::artifacts::fingerprint(include_bytes!(
            "../../../../packs/agents/_agents/native/tmux.py"
        )),
    );
    out.insert(
        "_agents/native/worktree.py".into(),
        sluice_store::artifacts::fingerprint(include_bytes!(
            "../../../../packs/agents/_agents/native/worktree.py"
        )),
    );
    out.insert(
        "_git/refs.py".into(),
        sluice_store::artifacts::fingerprint(include_bytes!("../../../../packs/git/_git/refs.py")),
    );
    out
}
