#!/usr/bin/env python3
"""Regenerate the locked graph without changing build environment variables."""
import json
from pathlib import Path
import subprocess
import tomllib

root = Path(__file__).resolve().parents[2]
cargo = ['cargo', '--config', f'build.target-dir="{root / "target"}"']
def run(*args):
    return subprocess.check_output([*cargo, *args], cwd=root, text=True)
metadata = json.loads(run('metadata', '--locked', '--format-version', '1'))
tree = run('tree', '--workspace', '--locked', '--target', 'all', '-e', 'normal,build,dev', '-f', '{p} [{f}]')
manifest = tomllib.loads((root / 'Cargo.toml').read_text())
nodes = {n['id']: n for n in metadata['resolve']['nodes']}
packages = {p['id']: p for p in metadata['packages']}
text = '''# Locked Rust dependencies

Generated by `uv run python docs/rust/generate_dependencies.py` from `cargo tree`
and `cargo metadata --locked`. Rust 1.97.0, edition 2024, resolver 3.

The tree below includes normal, build and dev edges for every target. A `(*)`
marks a repeated subtree whose edges appear elsewhere. Feature lists are the
resolved union, so a consumer's requested features can be smaller. Cargo.lock
pins every package and checksum. Tests and examples are included in the G0
`--workspace --all-targets` build; cross-platform entries are inventory, not
claims of cross-platform build acceptance.

## Direct dependencies

Defaults stay enabled unless the specification explicitly disables them or,
for the local Unix WebSocket, enabling only handshake avoids unnecessary TLS.
`schemars` uses its default derive support; ordered maps supply their schemas
without enabling extra integration features. `toml_edit`'s semantic pin is
`=0.25.15`; Cargo ignores build metadata in requirements. The lock retains the
specified published `0.25.15+spec-1.1.0` package.

| Dependency | Exact pin | Defaults | Requested features | Consumers |
|---|---|---|---|---|
'''
for name, dep in manifest['workspace']['dependencies'].items():
    if 'path' in dep:
        continue
    consumers = []
    for member in manifest['workspace']['members']:
        cm = tomllib.loads((root / member / 'Cargo.toml').read_text())
        for scope in ['dependencies', 'dev-dependencies']:
            if name in cm.get(scope, {}):
                consumers.append(cm['package']['name'] + (' tests' if scope == 'dev-dependencies' else ''))
    text += f'| {name} | `{dep["version"]}` | {"on" if dep.get("default-features", True) else "off"} | {", ".join(dep.get("features", [])) or "none"} | {", ".join(consumers)} |\n'
text += '''
## Native build requirements

The Linux graph builds bundled SQLite via `libsqlite3-sys` and the default
Rustls AWS-LC provider via `aws-lc-sys`. Their build dependencies include `cc`,
`pkg-config`, `vcpkg` and `cmake`. The successful G0 build used the installed C
compiler, assembler, make and CMake. SQLite's bundled feature supplies source;
no system SQLite library or OpenSSL is selected. `inotify-sys` declares its
system linkage. libc and procfs use Linux host interfaces without vendoring
another native implementation. The tmux 3.7c artifact is a separate P3.00 gate
and is not built or installed by phase 0.

The following table inventories **every locked package with a build script or
`links` declaration**, including target-only packages. A script does not imply
a native library: many generate version/cfg/data or proc-macro support.

| Package | Build script | Native `links` | Direct build dependencies | Resolved features |
|---|---|---|---|---|
'''
for p in sorted(packages.values(), key=lambda p: (p['name'], p['version'])):
    scripts = [Path(t['src_path']).name for t in p['targets'] if 'custom-build' in t['kind']]
    if not scripts and not p.get('links'):
        continue
    deps = []
    for d in nodes[p['id']]['deps']:
        if any(k['kind'] == 'build' for k in d['dep_kinds']):
            other = packages[d['pkg']]
            deps.append(other['name'] + ' ' + other['version'])
    text += f'| {p["name"]} {p["version"]} | {", ".join(scripts) or "none"} | {p.get("links") or "none"} | {", ".join(sorted(deps)) or "none"} | {", ".join(nodes[p["id"]]["features"]) or "none"} |\n'
text += '\n## Complete locked feature and edge graph\n\n```text\n' + tree.replace(str(root), '<workspace>') + '```\n'
(root / 'docs/rust/dependencies.md').write_text(text)
