[package]
name = "sluice-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sluice-model.workspace = true
rusqlite.workspace = true
tokio.workspace = true
tracing.workspace = true
time.workspace = true
fs4.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
sluice-process.workspace = true
